CREATE TABLE [FoodItems] (
  [FoodItemID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [FoodName] VARCHAR (255),
  [Manufacturer] VARCHAR (255),
  [ServingsPerContainer] DOUBLE,
  [ServingSize] VARCHAR (255),
  [Calories] DOUBLE,
  [TotalFat] DOUBLE,
  [SaturatedFat] DOUBLE,
  [TransFat] DOUBLE,
  [Cholesterol] DOUBLE,
  [Sodium] DOUBLE,
  [TotalCarbs] DOUBLE,
  [DietaryFiber] DOUBLE,
  [TotalSugars] DOUBLE,
  [AddedSugar] DOUBLE,
  [Protein] DOUBLE,
  [FoodDescription] LONGTEXT,
  [UrlLink] LONGTEXT,
  [CookingInstructions] LONGTEXT
)
