CREATE TABLE [Ingredients] (
  [IngredientID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Ingredient] VARCHAR (255),
  [Manufacturer] VARCHAR (255),
  [ServingDescription] LONGTEXT,
  [ServingAmount] DOUBLE,
  [ServingUnitID] LONG,
  [Calories] DOUBLE,
  [TotalFat] DOUBLE,
  [SaturatedFat] DOUBLE,
  [TransFat] DOUBLE,
  [Cholesterol] DOUBLE,
  [Sodium] DOUBLE,
  [TotalCarbs] DOUBLE,
  [DietaryFiber] DOUBLE,
  [TotalSugars] DOUBLE,
  [AddedSugar] DOUBLE,
  [Protein] DOUBLE,
  [VitaminD] DOUBLE,
  [Calcium] DOUBLE,
  [Iron] DOUBLE,
  [Potassium] DOUBLE,
  [UrlLink] LONGTEXT
)
