CREATE TABLE [Meals] (
  [MealID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [UserID] LONG CONSTRAINT [UsersMeals] REFERENCES [Users] ([UserID]),
  [MealDate] DATETIME,
  [FoodItemID] LONG CONSTRAINT [FoodItemsMeals] REFERENCES [FoodItems] ([FoodItemID]),
  [Servings] DOUBLE,
  [Calories] DOUBLE,
  [TotalFat] DOUBLE,
  [SaturatedFat] DOUBLE,
  [TransFat] DOUBLE,
  [Cholesterol] DOUBLE,
  [Sodium] DOUBLE,
  [TotalCarbs] DOUBLE,
  [DietaryFiber] DOUBLE,
  [TotalSugars] DOUBLE,
  [AddedSugar] DOUBLE,
  [Protein] DOUBLE,
  [VitaminD] DOUBLE,
  [Calcium] DOUBLE,
  [Iron] DOUBLE,
  [Potassium] DOUBLE
)
