CREATE TABLE [Meals] (
  [MealID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [UserID] LONG CONSTRAINT [UsersMeals] REFERENCES [Users] ([UserID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [MealDate] DATETIME,
  [FoodItemID] LONG CONSTRAINT [FoodItemsMeals] REFERENCES [FoodItems] ([FoodItemID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [Protein] LONG,
  [Sugar] LONG,
  [Calories] LONG
)
